name: Go

on: [push,pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Set up Environment Variable
      run: |
        export GOBIN=/home/runner/go/bin
        go env
        
    - name: Build
      run: |
        ls
        cd discovery/
        go get; go build;
        ls
        cd ../broker/
        go get; go build;
        ls
        cd ../designer/
        npm install 
        ls
        cd ../master/
        go get; go build;
        ls
      
