name: Go

on: [push,pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Docker Build Job
      run: |
        export GOBIN=/home/runner/go/bin
        docker --version
        echo "build discovery"
        cd discovery
        pwd
        sh build

        echo "build broker"
        cd ../broker
        pwd
        sh build

        echo "build worker"
        cd ../worker
        pwd
        sh build

        echo "build master"
        cd ../master
        pwd
        sh build
    
        echo "build designer"
        cd ../master
        pwd
        sh build
            
    - name: Build
      run: |
        sudo docker run --rm -it -d -p 8082:8080 -p 9082:9080 -p 8000:8000 -v ~/dgraph:/dgraph fogflow/dgraph:latest
        sudo docker run --rm -it -d --name mongodb -d mongo:3.4
        sudo docker run --rm -it -d --name orion1 --link mongodb:mongodb -p 1026:1026 fiware/orion -dbhost mongodb
        docker ps -a 
        export GOBIN=/home/runner/go/bin
        ls
        cd discovery/
        go get; go build;
        ls
        cd ../broker/
        go get; go build;
        ls
        cd ../designer/
        npm install 
        
        sudo apt-get update
        sudo apt-get install jq
        sudo apt-get install python-pip
        pip -V
        sudo pip install --upgrade pip
        pip install Flask
        pip install requests
        pip install -U pytest
        sudo apt-get install curl
        echo 'deb http://www.rabbitmq.com/debian/ testing main' | sudo tee /etc/apt/sources.list.d/rabbitmq.list
        wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install rabbitmq-server
        sudo update-rc.d rabbitmq-server defaults
        sudo service rabbitmq-server start
        sudo systemctl enable rabbitmq-server
        sudo systemctl start rabbitmq-server
        sudo rabbitmqctl add_user admin mypass
        sudo rabbitmqctl set_user_tags admin administrator
        sudo rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
        echo "Done"
      
