name: Go

on: [push,pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        export PATH=$PATH:$GOPATH/bin:/home/runner/go/bin
        go env
        ls
        cd discovery/
        go get; go build;
        la
        cd ../broker/
        go get; go build;
        la
        cd ../designer
        npm install 
        
      
