name: Go

on: [push,pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Docker Build Job
      run: |
        docker --version
        echo "build discovery"
        cd discovery
        pwd
        sh build

        echo "build broker"
        cd ../broker
        pwd
        sh build

        echo "build worker"
        cd ../worker
        pwd
        sh build

        echo "build master"
        cd ../master
        pwd
        sh build
    
        echo "build designer"
        cd ../master
        pwd
        sh build
            
    - name: Build
      run: |
        export GOBIN=/home/runner/go/bin
        ls
        cd discovery/
        go get; go build;
        ls
        cd ../broker/
        go get; go build;
        ls
        cd ../designer/
        npm install 
        ls
        cd ../master/
        go get; go build;
        ls
        docker --version
      
